title: NYC
description: My Personal Stack Problems
author: Namyoung Kim(Leo)
author_1: Agus Makmun
github: https://github.com/namyoungkim
about: Data Scientist
disqus_shortname: NYC
google_analytics: 
avatar_url: /static/img/pro.jpeg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/namyoung-kim-734814112/"
    - icon: fa-github
      link: "https://github.com/namyoungkim"

share:

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://namyoungkim.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-latex

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
