title: NYC (Leo)
description: Data Scientist
author: Namyoung Kim(Leo)
github: https://github.com/namyoungkim
about: Data-driven is my life.
disqus_shortname: NYC
google_analytics: UA-116039433-1
avatar_url: /static/img/pro.png

enableTags: true
tagarray: []

collections:
  featured_categories:
    permalink: /category/:name/
    output: true
  featured_tags:
    permalink: /tag/:name/
    output: true
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/namyoung-kim-734814112/"
    - icon: fa-github
      link: "https://github.com/namyoungkim"

share:

urls:
    - text: Statistics
      url: /category/statistics/
    - text: Linear-Algebra
      url: /category/Linear_Algebra/
    - text: Visualization
      url: /category/Visualization/
    - text: Machine-Learning
      url: /category/machine-learning/
    - text: Deep-Learning
      url: /category/deep-learning/
    - text: Python
      url: /category/python/
    - text: SQL
      url: /category/sql/
    - text: My Projects
      url: /projects/
    - text: About Me
      url: /about/
    - text: ETC
      url: /category/etc/

url: "https://namyoungkim.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-latex

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

permalink: pretty

# The font used for headings. Expects a string that is a valid CSS font-family value.
font_heading:        "'Lato', 'Sans-serif'"

# The text font. Expects a string that is a valid CSS font-family value.
font:                "'Lato', 'Sans-serif'"

# The string encoding what fonts to fetch from Google Fonts.
# See: https://qwtel.com/hydejack/docs/configuration/
google_fonts:        Lato