title: NYC (Leo)
description: Data Scientist
author: Namyoung Kim(Leo)
github: https://github.com/namyoungkim
about: Data-driven is my life.
disqus_shortname: NYC
google_analytics: UA-116039433-1
avatar_url: /static/img/pro.png

enableTags: true
tagarray: []

collections:
  category:
    permalink: /category/:name/
    output: true
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/namyoung-kim-734814112/"
    - icon: fa-github
      link: "https://github.com/namyoungkim"

share:

urls:
    - text: statistics
      url: /category/statistics
    - text: Linear_Algebra
      url: /category/Linear_Algebra
    - text: visualization
      url: /category/visualization
    - text: machine_learning
      url: /category/machine_learning
    - text: deep_learning
      url: /category/deep_learning
    - text: python
      url: /category/python
    - text: sql
      url: /category/sql
    - text: My Projects
      url: /projects/
    - text: About Me
      url: /about/
    - text: etc
      url: /category/etc

url: "https://namyoungkim.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-latex

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

permalink: pretty

# The font used for headings. Expects a string that is a valid CSS font-family value.
font_heading:        "'Lato', 'Sans-serif'"

# The text font. Expects a string that is a valid CSS font-family value.
font:                "'Lato', 'Sans-serif'"

# The string encoding what fonts to fetch from Google Fonts.
# See: https://qwtel.com/hydejack/docs/configuration/
google_fonts:        Lato